disabled_rules:
- colon
- comma
- control_statement
- line_length
- identifier_name
​
opt_in_rules:
- empty_count
- missing_docs
​
excluded:
- Carthage
- Pods
​
file_length:
    warning: 500
    error: 600
​
warning_threshold: 15
​
reporter: "xcode"
